# Generated by Django 6.0.4 on 2026-05-31 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Ota-ona telefoni')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yosh')),
                ('source', models.CharField(choices=[('website', 'Veb-sayt'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('friend', "Tanish/Do'st"), ('banner', 'Reklama banneri'), ('other', 'Boshqa')], default='website', max_length=20, verbose_name='Qayerdan')),
                ('message', models.TextField(blank=True, verbose_name='Xabar / Izoh')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('trial', 'Sinov darsida'), ('enrolled', "Ro'yxatga olindi"), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holat')),
                ('staff_note', models.TextField(blank=True, verbose_name='Xodim izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul xodim")),
                ('converted_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='students.student', verbose_name="Yaratilgan o'quvchi")),
                ('preferred_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='courses.course', verbose_name='Tanlangan guruh')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='courses.subject', verbose_name="Qiziqqan yo'nalish")),
            ],
            options={
                'verbose_name': 'Onlayn ariza',
                'verbose_name_plural': 'Onlayn arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Oylik to'lov")),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Chegirma (%)')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Boshlangan sana')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugagan sana')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('frozen', 'Muzlatilgan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Yozilish',
                'verbose_name_plural': 'Yozilishlar',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
