# Generated by Django 6.0.4 on 2026-06-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, help_text="Bot orqali kelgan arizada to'ldiriladi (kabinet havolasini yuborish uchun).", max_length=32, verbose_name='Telegram chat ID'),
        ),
    ]
