# Generated by Django 6.0.4 on 2026-06-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='month',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Oy'),
        ),
    ]
