# Generated by Django 6.0.4 on 2026-05-31 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Ota-ona telefoni')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('gender', models.CharField(choices=[('male', "O'g'il bola"), ('female', 'Qiz bola')], default='male', max_length=10, verbose_name='Jinsi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('school_name', models.CharField(blank=True, max_length=150, verbose_name='Maktab')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='Sinf')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Rasm')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('frozen', 'Muzlatilgan'), ('graduated', 'Bitirgan'), ('left', 'Tark etgan')], default='active', max_length=20, verbose_name='Holat')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Manfiy = qarzdor', max_digits=12, verbose_name="Balans (so'm)")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
                'ordering': ['-created_at'],
            },
        ),
    ]
