# Generated by Django 6.0.4 on 2026-06-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, help_text="O'quvchi bot orqali ro'yxatdan o'tganda to'ldiriladi (bot xabar yuborish uchun).", max_length=32, verbose_name='Telegram chat ID'),
        ),
    ]
