# -*- coding: utf-8 -*-
"""Bir martalik skript: locale/en va locale/ru django.po fayllarini to'ldiradi.
Ishlatilgach o'chiriladi. Tarjimalar uz -> (en, ru)."""
import polib

# msgid -> (english, russian)
T = {
    # --- accounts/decorators.py ---
    "Sizda bu sahifaga ruxsat yo'q.": ("You don't have access to this page.", "У вас нет доступа к этой странице."),
    "Bu bo'limga faqat xodimlar kira oladi.": ("Only staff can access this section.", "В этот раздел могут входить только сотрудники."),
    "Ruxsat yo'q.": ("Access denied.", "Доступ запрещён."),
    "Bu amal faqat administrator/direktor uchun.": ("This action is for administrators/directors only.", "Это действие доступно только администратору/директору."),
    # --- accounts/forms.py ---
    "Tasdiqlash usuli": ("Verification method", "Способ подтверждения"),
    "Telegram bot": ("Telegram bot", "Telegram-бот"),
    "Gmail": ("Gmail", "Gmail"),
    "Lavozim": ("Position", "Должность"),
    "Administrator": ("Administrator", "Администратор"),
    "Direktor": ("Director", "Директор"),
    "Ism": ("First name", "Имя"),
    "Ismingiz": ("Your first name", "Ваше имя"),
    "Familiya": ("Last name", "Фамилия"),
    "Familiyangiz": ("Your last name", "Ваша фамилия"),
    "Login": ("Login", "Логин"),
    "login (keyin shu bilan kirasiz)": ("login (you'll sign in with it)", "логин (с ним вы будете входить)"),
    "Tizimga kirish uchun login. Faqat harf, raqam va _ belgisi.": ("Login for signing in. Letters, digits and _ only.", "Логин для входа. Только буквы, цифры и _."),
    "Telegram ID": ("Telegram ID", "Telegram ID"),
    "Botdan olingan ID raqami": ("ID number from the bot", "ID, полученный от бота"),
    "Botni oching va «🆔 ID raqamim» tugmasini bosib, raqamni shu yerga kiriting.": ("Open the bot, tap «🆔 My ID» and enter the number here.", "Откройте бота, нажмите «🆔 Мой ID» и введите номер сюда."),
    "Email (Gmail)": ("Email (Gmail)", "Email (Gmail)"),
    "Tasdiqlash kodi shu manzilga yuboriladi.": ("The verification code will be sent to this address.", "Код подтверждения будет отправлен на этот адрес."),
    "Telefon": ("Phone", "Телефон"),
    "Parol": ("Password", "Пароль"),
    "Kamida 6 ta belgi": ("At least 6 characters", "Не менее 6 символов"),
    "Parolni takrorlang": ("Repeat password", "Повторите пароль"),
    "Parolni qayta kiriting": ("Re-enter the password", "Введите пароль ещё раз"),
    "Login majburiy.": ("Login is required.", "Логин обязателен."),
    "Login faqat harf, raqam va _ belgisidan iborat bo'lsin.": ("Login may contain only letters, digits and _.", "Логин может содержать только буквы, цифры и _."),
    "Bu login band. Boshqasini tanlang.": ("This login is taken. Choose another.", "Этот логин занят. Выберите другой."),
    "Telegram ID faqat raqamlardan iborat (botdan oling).": ("Telegram ID contains only digits (get it from the bot).", "Telegram ID состоит только из цифр (получите у бота)."),
    "Bu email allaqachon ro'yxatdan o'tgan.": ("This email is already registered.", "Этот email уже зарегистрирован."),
    "Direktor allaqachon mavjud. Yangi direktor qo'sha olmaysiz.": ("A director already exists. You cannot add a new one.", "Директор уже существует. Добавить нового нельзя."),
    "Administratorlar soni to'lgan.": ("The administrator limit is reached.", "Лимит администраторов исчерпан."),
    "Gmail orqali ro'yxatdan o'tish uchun email kiriting.": ("Enter an email to register via Gmail.", "Укажите email для регистрации через Gmail."),
    "Telegram bot orqali ro'yxatdan o'tish uchun ID kiriting.": ("Enter an ID to register via the Telegram bot.", "Укажите ID для регистрации через Telegram-бота."),
    "Parollar mos kelmadi.": ("Passwords do not match.", "Пароли не совпадают."),
    "O'qituvchi": ("Teacher", "Преподаватель"),
    "O'quvchi": ("Student", "Ученик"),
    "Rol": ("Role", "Роль"),
    "Loginingiz (yoki email)": ("Your login (or email)", "Ваш логин (или email)"),
    "Parolingiz": ("Your password", "Ваш пароль"),
    "Tasdiqlash kodi": ("Verification code", "Код подтверждения"),
    "Kod faqat raqamlardan iborat.": ("The code contains digits only.", "Код состоит только из цифр."),
    "Telegram ID faqat raqamlardan iborat.": ("Telegram ID contains only digits.", "Telegram ID состоит только из цифр."),
    "Email manzilingizni kiriting.": ("Enter your email address.", "Введите ваш email."),
    "Telegram ID raqamingizni kiriting.": ("Enter your Telegram ID.", "Введите ваш Telegram ID."),
    "Yangi parol": ("New password", "Новый пароль"),
    "Bo'sh qoldirilsa — avtomatik / o'zgarmaydi": ("If left empty — auto / unchanged", "Если оставить пустым — авто / без изменений"),
    "Yangi foydalanuvchi uchun majburiy. Tahrirda bo'sh = parol o'zgarmaydi.": ("Required for a new user. Empty when editing = password unchanged.", "Обязателен для нового пользователя. Пусто при редактировании = пароль не меняется."),
    "email (ixtiyoriy)": ("email (optional)", "email (необязательно)"),
    "Telegram ID (ixtiyoriy)": ("Telegram ID (optional)", "Telegram ID (необязательно)"),
    "Login (username) majburiy.": ("Login (username) is required.", "Логин (username) обязателен."),
    "Yangi foydalanuvchi uchun parol majburiy.": ("Password is required for a new user.", "Пароль обязателен для нового пользователя."),
    "Joriy parol": ("Current password", "Текущий пароль"),
    "Hozirgi parolingiz": ("Your current password", "Ваш текущий пароль"),
    "Yangi parolni takrorlang": ("Repeat new password", "Повторите новый пароль"),
    "Joriy parol noto'g'ri.": ("Current password is incorrect.", "Текущий пароль неверен."),
    "Yangi parollar mos kelmadi.": ("New passwords do not match.", "Новые пароли не совпадают."),
    "Rasm": ("Photo", "Фото"),
    "Google rasmi": ("Google photo", "Фото Google"),
    "Telegram chat ID": ("Telegram chat ID", "Telegram chat ID"),
    "Telegram bot bergan ID — tasdiqlash kodi shu yerga yuboriladi.": ("ID given by the Telegram bot — the verification code is sent here.", "ID, выданный Telegram-ботом — сюда отправляется код подтверждения."),
    "Tasdiqlangan": ("Verified", "Подтверждён"),
    "Ko'rinadigan parol": ("Visible password", "Видимый пароль"),
    "Admin yaratgan parol — faqat admin panelida ko'rinadi.": ("Password set by the admin — visible only in the admin panel.", "Пароль, заданный администратором — виден только в панели администратора."),
    "Parol yangilanishi shart": ("Password change required", "Требуется смена пароля"),
    "Foydalanuvchi": ("User", "Пользователь"),
    "Foydalanuvchilar": ("Users", "Пользователи"),
    "Ro'yxatdan o'tish": ("Sign up", "Регистрация"),
    "Parolni tiklash": ("Reset password", "Сброс пароля"),
    "Kanal": ("Channel", "Канал"),
    "Email": ("Email", "Email"),
    "Kod": ("Code", "Код"),
    "Maqsad": ("Purpose", "Цель"),
    "Ma'lumotlar": ("Data", "Данные"),
    "Urinishlar": ("Attempts", "Попытки"),
    "Ishlatilgan": ("Used", "Использован"),
    "Amal qilish muddati": ("Expiry time", "Срок действия"),
    "Tasdiqlash kodlari": ("Verification codes", "Коды подтверждения"),
    "Kutilmoqda": ("Pending", "Ожидает"),
    "Yangi parol berildi": ("New password issued", "Новый пароль выдан"),
    "Rad etildi": ("Rejected", "Отклонено"),
    "Login / telefon": ("Login / phone", "Логин / телефон"),
    "Foydalanuvchi botda kiritgan login yoki telefon.": ("Login or phone the user entered in the bot.", "Логин или телефон, введённый пользователем в боте."),
    "Ism (botdan)": ("Name (from bot)", "Имя (из бота)"),
    "Holat": ("Status", "Статус"),
    "Topilgan foydalanuvchi": ("Matched user", "Найденный пользователь"),
    "Hal qilgan admin": ("Resolved by admin", "Решено администратором"),
    "Izoh": ("Note", "Примечание"),
    "Parol tiklash murojaati": ("Password reset request", "Запрос на сброс пароля"),
    "Parol tiklash murojaatlari": ("Password reset requests", "Запросы на сброс пароля"),
    # --- accounts/views.py messages ---
    "Login yoki parol noto'g'ri.": ("Invalid login or password.", "Неверный логин или пароль."),
    "Hisobingiz faollashtirilmagan. Administratorga murojaat qiling.": ("Your account is not activated. Contact the administrator.", "Ваша учётная запись не активирована. Обратитесь к администратору."),
    "Siz «%(role)s» sifatida ro'yxatdan o'tmagansiz. Iltimos, to'g'ri rolni tanlang.": ("You are not registered as «%(role)s». Please choose the correct role.", "Вы не зарегистрированы как «%(role)s». Пожалуйста, выберите правильную роль."),
    "Administratorlar soni cheklangan (%(limit)s ta). Siz ushbu hisob bilan administrator sifatida kira olmaysiz.": ("The number of administrators is limited (%(limit)s). You cannot sign in as an administrator with this account.", "Количество администраторов ограничено (%(limit)s). Вы не можете войти администратором с этой учётной записью."),
    "Xavfsizlik uchun yangi parol o'rnating.": ("Set a new password for security.", "Установите новый пароль в целях безопасности."),
    "Xush kelibsiz, %(name)s!": ("Welcome, %(name)s!", "Добро пожаловать, %(name)s!"),
    "Kod yuborilmadi. Email manzilingiz to'g'ri ekanini tekshiring va qaytadan urinib ko'ring.": ("The code was not sent. Check that your email is correct and try again.", "Код не отправлен. Проверьте правильность email и попробуйте снова."),
    "Kod yuborilmadi. Botni oching, «🆔 ID raqamim» tugmasini bosib, ID raqamingiz to'g'ri ekanini tekshiring va qaytadan urinib ko'ring.": ("The code was not sent. Open the bot, tap «🆔 My ID», check that your ID is correct and try again.", "Код не отправлен. Откройте бота, нажмите «🆔 Мой ID», проверьте правильность ID и попробуйте снова."),
    "Tasdiqlash kodi email manzilingizga yuborildi.": ("The verification code was sent to your email.", "Код подтверждения отправлен на ваш email."),
    "Tasdiqlash kodi Telegram botingizga yuborildi.": ("The verification code was sent to your Telegram bot.", "Код подтверждения отправлен в ваш Telegram-бот."),
    "Avval ro'yxatdan o'ting.": ("Please register first.", "Сначала зарегистрируйтесь."),
    "Kod eskirgan yoki topilmadi. Qaytadan yuboring.": ("The code expired or was not found. Send it again.", "Код устарел или не найден. Отправьте заново."),
    "Kod noto'g'ri. Qolgan urinishlar: %(left)s.": ("Incorrect code. Attempts left: %(left)s.", "Неверный код. Осталось попыток: %(left)s."),
    "Hisobingiz yaratildi. Login: %(username)s. Siz %(role)s sifatida kirdingiz.": ("Your account has been created. Login: %(username)s. You are signed in as %(role)s.", "Ваша учётная запись создана. Логин: %(username)s. Вы вошли как %(role)s."),
    "Tasdiqlandi. Endi yangi parol o'rnating.": ("Verified. Now set a new password.", "Подтверждено. Теперь установите новый пароль."),
    "Iltimos, %(seconds)s soniyadan so'ng qayta urining.": ("Please try again in %(seconds)s seconds.", "Пожалуйста, повторите через %(seconds)s секунд."),
    "Yangi kod yuborildi.": ("A new code has been sent.", "Новый код отправлен."),
    "Kodni yuborishda xatolik yuz berdi.": ("An error occurred while sending the code.", "Произошла ошибка при отправке кода."),
    "Kodni yuborishda xatolik. Ma'lumotlaringizni tekshiring.": ("Error sending the code. Check your details.", "Ошибка отправки кода. Проверьте свои данные."),
    "Agar bu email ro'yxatdan o'tgan bo'lsa, kod yuborildi.": ("If this email is registered, a code has been sent.", "Если этот email зарегистрирован, код отправлен."),
    "Agar bu ID ro'yxatdan o'tgan bo'lsa, kod botingizga yuborildi.": ("If this ID is registered, a code has been sent to your bot.", "Если этот ID зарегистрирован, код отправлен в ваш бот."),
    "Avval kod bilan tasdiqlang.": ("Verify with a code first.", "Сначала подтвердите кодом."),
    "Foydalanuvchi topilmadi.": ("User not found.", "Пользователь не найден."),
    "Parol yangilandi. Endi kirishingiz mumkin.": ("Password updated. You can sign in now.", "Пароль обновлён. Теперь вы можете войти."),
    "Parol muvaffaqiyatli yangilandi.": ("Password updated successfully.", "Пароль успешно обновлён."),
    "Bu murojaat allaqachon ko'rib chiqilgan.": ("This request has already been processed.", "Этот запрос уже обработан."),
    "Murojaat rad etildi.": ("The request was rejected.", "Запрос отклонён."),
    "Foydalanuvchi topilmadi. Login (username) ni qo'lda kiriting va qaytadan urinib ko'ring.": ("User not found. Enter the login (username) manually and try again.", "Пользователь не найден. Введите логин (username) вручную и попробуйте снова."),
    "Parol kamida 6 ta belgidan iborat bo'lishi kerak.": ("The password must be at least 6 characters.", "Пароль должен содержать не менее 6 символов."),
    "Yangi parol o'rnatildi va %(username)s ga botga yuborildi.": ("A new password was set and sent to %(username)s via the bot.", "Новый пароль установлен и отправлен %(username)s в бот."),
    "Parol o'rnatildi (%(username)s), lekin botga yuborilmadi (bot tokeni yoki chat ID yo'q). Parolni qo'lda yetkazing: %(password)s": ("Password set (%(username)s), but not sent to the bot (no bot token or chat ID). Deliver the password manually: %(password)s", "Пароль установлен (%(username)s), но не отправлен в бот (нет токена бота или chat ID). Передайте пароль вручную: %(password)s"),
    "Foydalanuvchi yaratildi — login: %(username)s, parol: %(password)s": ("User created — login: %(username)s, password: %(password)s", "Пользователь создан — логин: %(username)s, пароль: %(password)s"),
    "%(username)s ma'lumotlari saqlandi.": ("%(username)s details saved.", "Данные %(username)s сохранены."),
    " (botga yuborildi)": (" (sent to the bot)", " (отправлено в бот)"),
    "%(username)s uchun yangi parol: %(password)s%(suffix)s": ("New password for %(username)s: %(password)s%(suffix)s", "Новый пароль для %(username)s: %(password)s%(suffix)s"),
    "O'zingizni o'chira olmaysiz.": ("You can't delete yourself.", "Вы не можете удалить самого себя."),
    "%(name)s o'chirildi.": ("%(name)s deleted.", "%(name)s удалён."),
    "Siz %(name)s hisobiga kirdingiz (admin sifatida).": ("You signed in as %(name)s (as admin).", "Вы вошли в учётную запись %(name)s (как администратор)."),
    "Admin hisobingizga qaytdingiz.": ("You returned to your admin account.", "Вы вернулись в свою учётную запись администратора."),
    "Parolingiz muvaffaqiyatli o'zgartirildi.": ("Your password was changed successfully.", "Ваш пароль успешно изменён."),
    "Markaz ma'lumotlari saqlandi.": ("Center details saved.", "Данные центра сохранены."),
    "Profil ma'lumotlari saqlandi.": ("Profile details saved.", "Данные профиля сохранены."),
    "Rasm tanlanmadi.": ("No image selected.", "Изображение не выбрано."),
    "Rasm hajmi 5 MB dan oshmasligi kerak.": ("The image must not exceed 5 MB.", "Размер изображения не должен превышать 5 МБ."),
    "Faqat rasm fayli yuklang.": ("Upload an image file only.", "Загрузите только файл изображения."),
    "Profil rasmingiz yangilandi.": ("Your profile photo was updated.", "Ваше фото профиля обновлено."),
    "Tizimdan chiqdingiz.": ("You have signed out.", "Вы вышли из системы."),
    # --- cabinet/views.py ---
    "Sizning hisobingiz hali o'quvchi profiliga bog'lanmagan. Markaz ma'muriyatiga murojaat qiling.": ("Your account is not linked to a student profile yet. Contact the center administration.", "Ваша учётная запись ещё не связана с профилем ученика. Обратитесь в администрацию центра."),
    "O'quvchi profili topilmadi.": ("Student profile not found.", "Профиль ученика не найден."),
    "A'lo": ("Excellent", "Отлично"),
    "Yaxshi": ("Good", "Хорошо"),
    "Qoniqarli": ("Satisfactory", "Удовлетворительно"),
    "Past": ("Low", "Низко"),
    "Baho yo'q": ("No grades", "Нет оценок"),
    # --- courses/forms.py & models ---
    "Masalan: Ingliz tili — kechki guruh": ("E.g.: English — evening group", "Напр.: Английский — вечерняя группа"),
    "Nomi": ("Name", "Название"),
    "Tavsif": ("Description", "Описание"),
    "Rang": ("Color", "Цвет"),
    "Belgi (emoji)": ("Icon (emoji)", "Значок (эмодзи)"),
    "Faol": ("Active", "Активен"),
    "Yo'nalish": ("Subject", "Направление"),
    "Yo'nalishlar": ("Subjects", "Направления"),
    "Qabul ochiq": ("Enrolling", "Идёт набор"),
    "Davom etmoqda": ("Ongoing", "Идёт"),
    "Yakunlangan": ("Finished", "Завершён"),
    "Vaqtincha to'xtatilgan": ("Paused", "Приостановлен"),
    "Du-Chor-Juma": ("Mon-Wed-Fri", "Пн-Ср-Пт"),
    "Se-Pay-Shan": ("Tue-Thu-Sat", "Вт-Чт-Сб"),
    "Har kuni": ("Every day", "Каждый день"),
    "Dam olish kunlari": ("Weekends", "Выходные дни"),
    "Guruh nomi": ("Group name", "Название группы"),
    "Daraja / level": ("Level", "Уровень"),
    "Masalan: Beginner, Elementary, Intermediate, A1, B2 ...": ("E.g.: Beginner, Elementary, Intermediate, A1, B2 ...", "Напр.: Beginner, Elementary, Intermediate, A1, B2 ..."),
    "Oylik to'lov (so'm)": ("Monthly fee (soʻm)", "Ежемесячная оплата (сум)"),
    "Davomiyligi (oy)": ("Duration (months)", "Длительность (мес.)"),
    "Sig'im (max o'quvchi)": ("Capacity (max students)", "Вместимость (макс. учеников)"),
    "Dars kunlari": ("Class days", "Дни занятий"),
    "Boshlanish vaqti": ("Start time", "Время начала"),
    "Xona": ("Room", "Кабинет"),
    "Boshlanish sanasi": ("Start date", "Дата начала"),
    "Guruh": ("Group", "Группа"),
    "Guruhlar": ("Groups", "Группы"),
    "'%(name)s' guruhi yaratildi.": ("Group '%(name)s' created.", "Группа '%(name)s' создана."),
    "Yangi guruh": ("New group", "Новая группа"),
    "Guruh ma'lumotlari yangilandi.": ("Group details updated.", "Данные группы обновлены."),
    "Tahrirlash — %(name)s": ("Edit — %(name)s", "Редактирование — %(name)s"),
    "Guruh o'chirildi.": ("Group deleted.", "Группа удалена."),
    "Yo'nalish qo'shildi.": ("Subject added.", "Направление добавлено."),
    "Yangi yo'nalish": ("New subject", "Новое направление"),
    "Yo'nalish yangilandi.": ("Subject updated.", "Направление обновлено."),
    "Yo'nalishni tahrirlash": ("Edit subject", "Редактировать направление"),
    # --- dashboard weekdays ---
    "Dushanba": ("Monday", "Понедельник"),
    "Seshanba": ("Tuesday", "Вторник"),
    "Chorshanba": ("Wednesday", "Среда"),
    "Payshanba": ("Thursday", "Четверг"),
    "Juma": ("Friday", "Пятница"),
    "Shanba": ("Saturday", "Суббота"),
    "Yakshanba": ("Sunday", "Воскресенье"),
    "O'qituvchi panelini ko'rish uchun ro'yxatdan o'qituvchini tanlang.": ("Select a teacher from the list to view their panel.", "Выберите преподавателя из списка, чтобы открыть его панель."),
    # --- enrollments ---
    "Ism Familiya": ("First and last name", "Имя Фамилия"),
    "+998 (ixtiyoriy)": ("+998 (optional)", "+998 (необязательно)"),
    "Yosh": ("Age", "Возраст"),
    "Qo'shimcha izoh": ("Additional note", "Дополнительный комментарий"),
    "Yo'nalishni tanlang": ("Choose a subject", "Выберите направление"),
    "Yangi": ("New", "Новая"),
    "Bog'lanildi": ("Contacted", "Связались"),
    "Sinov darsida": ("Trial lesson", "На пробном уроке"),
    "Ro'yxatga olindi": ("Enrolled", "Зачислен"),
    "Veb-sayt": ("Website", "Веб-сайт"),
    "Instagram": ("Instagram", "Instagram"),
    "Telegram": ("Telegram", "Telegram"),
    "Tanish/Do'st": ("Acquaintance/Friend", "Знакомый/Друг"),
    "Reklama banneri": ("Ad banner", "Рекламный баннер"),
    "Boshqa": ("Other", "Другое"),
    "F.I.O": ("Full name", "Ф.И.О"),
    "Ota-ona telefoni": ("Parent's phone", "Телефон родителя"),
    "Qiziqqan yo'nalish": ("Subject of interest", "Интересующее направление"),
    "Tanlangan guruh": ("Selected group", "Выбранная группа"),
    "Qayerdan": ("Source", "Откуда узнали"),
    "Xabar / Izoh": ("Message / Note", "Сообщение / Примечание"),
    "Bot orqali kelgan arizada to'ldiriladi (kabinet havolasini yuborish uchun).": ("Filled in for applications from the bot (to send the cabinet link).", "Заполняется для заявок из бота (для отправки ссылки на кабинет)."),
    "Mas'ul xodim": ("Responsible staff", "Ответственный сотрудник"),
    "Yaratilgan o'quvchi": ("Created student", "Созданный ученик"),
    "Xodim izohi": ("Staff note", "Комментарий сотрудника"),
    "Yuborilgan vaqt": ("Submitted at", "Время отправки"),
    "Onlayn ariza": ("Online application", "Онлайн-заявка"),
    "Onlayn arizalar": ("Online applications", "Онлайн-заявки"),
    "Muzlatilgan": ("Frozen", "Заморожен"),
    "Bekor qilingan": ("Cancelled", "Отменён"),
    "Oylik to'lov": ("Monthly fee", "Ежемесячная оплата"),
    "Chegirma (%)": ("Discount (%)", "Скидка (%)"),
    "Boshlangan sana": ("Start date", "Дата начала"),
    "Tugagan sana": ("End date", "Дата окончания"),
    "Yozilish": ("Enrollment", "Зачисление"),
    "Yozilishlar": ("Enrollments", "Зачисления"),
    "Ariza holati yangilandi.": ("Application status updated.", "Статус заявки обновлён."),
    "Bu ariza allaqachon o'quvchiga aylantirilgan.": ("This application has already been converted to a student.", "Эта заявка уже преобразована в ученика."),
    "Onlayn arizadan (%(source)s).": ("From an online application (%(source)s).", "Из онлайн-заявки (%(source)s)."),
    "%(name)s tasdiqlandi. Shaxsiy kabinet havolasi, login (%(username)s) va parol o'quvchining Telegram'iga yuborildi.": ("%(name)s confirmed. The cabinet link, login (%(username)s) and password were sent to the student's Telegram.", "%(name)s подтверждён. Ссылка на кабинет, логин (%(username)s) и пароль отправлены в Telegram ученика."),
    "%(name)s o'quvchilarga qo'shildi. Login: %(username)s · Parol: %(password)s (Telegram ulanmagani uchun bu ma'lumotni o'zingiz yetkazing).": ("%(name)s added to students. Login: %(username)s · Password: %(password)s (Telegram is not linked, so deliver this info yourself).", "%(name)s добавлен в ученики. Логин: %(username)s · Пароль: %(password)s (Telegram не подключён, передайте эти данные сами)."),
    "O'quvchi guruhga yozildi.": ("The student was enrolled in the group.", "Ученик записан в группу."),
    "Yangi yozilish": ("New enrollment", "Новое зачисление"),
    "Yozilish yangilandi.": ("Enrollment updated.", "Зачисление обновлено."),
    "Yozilishni tahrirlash": ("Edit enrollment", "Редактировать зачисление"),
    "Yozilish o'chirildi.": ("Enrollment deleted.", "Зачисление удалено."),
    # --- instructors ---
    "Mutaxassislik / fan": ("Specialty / subject", "Специальность / предмет"),
    "Masalan: Matematika": ("E.g.: Mathematics", "Напр.: Математика"),
    "Tajriba (yil)": ("Experience (years)", "Опыт (лет)"),
    "Oylik (so'm)": ("Salary (soʻm)", "Оклад (сум)"),
    "Qisqacha ma'lumot": ("Short bio", "Краткая информация"),
    "Bio (ixtiyoriy)": ("Bio (optional)", "Био (необязательно)"),
    "Login (username)": ("Login (username)", "Логин (username)"),
    "Bo'sh — avtomatik": ("Empty — automatic", "Пусто — автоматически"),
    "Bo'sh — avtomatik xavfsiz parol": ("Empty — automatic secure password", "Пусто — автоматический надёжный пароль"),
    "Bu login band — boshqasini tanlang yoki bo'sh qoldiring.": ("This login is taken — choose another or leave it empty.", "Этот логин занят — выберите другой или оставьте пустым."),
    "To‘liq ism": ("Full name", "Полное имя"),
    "Mutaxassislik": ("Specialty", "Специальность"),
    "Tajriba yili": ("Years of experience", "Лет опыта"),
    "Oylik": ("Salary", "Оклад"),
    "Qisqacha ma’lumot": ("Short bio", "Краткая информация"),
    "To'liq ism": ("Full name", "Полное имя"),
    "Bio": ("Bio", "Био"),
    "O'qituvchilar": ("Teachers", "Преподаватели"),
    "✅ O'qituvchi «%(name)s» qo'shildi. Kirish — Login: %(username)s · Parol: %(password)s (ushbu ma'lumotni o'qituvchiga yetkazing).": ("✅ Teacher «%(name)s» added. Sign-in — Login: %(username)s · Password: %(password)s (deliver this info to the teacher).", "✅ Преподаватель «%(name)s» добавлен. Вход — Логин: %(username)s · Пароль: %(password)s (передайте эти данные преподавателю)."),
    "O'qituvchi ma'lumotlari yangilandi.": ("Teacher details updated.", "Данные преподавателя обновлены."),
    "O'qituvchi ro'yxatdan chiqarildi.": ("The teacher was removed.", "Преподаватель снят с учёта."),
    # --- monitoring models ---
    "Keldi": ("Present", "Пришёл"),
    "Kelmadi": ("Absent", "Не пришёл"),
    "Kechikdi": ("Late", "Опоздал"),
    "Sababli": ("Excused", "По уважительной"),
    "Sana": ("Date", "Дата"),
    "Davomat": ("Attendance", "Посещаемость"),
    "Joriy baho": ("Current grade", "Текущая оценка"),
    "Uy ishi": ("Homework", "Домашнее задание"),
    "Test / Quiz": ("Test / Quiz", "Тест / Викторина"),
    "Imtihon": ("Exam", "Экзамен"),
    "Og'zaki": ("Oral", "Устный"),
    "Turi": ("Type", "Тип"),
    "Ball": ("Score", "Балл"),
    "Maksimal ball": ("Maximum score", "Максимальный балл"),
    "Foiz": ("Percentage", "Процент"),
    "Baho": ("Grade", "Оценка"),
    "Baholar": ("Grades", "Оценки"),
    "Mavzu": ("Topic", "Тема"),
    "Uyga vazifa": ("Homework", "Домашнее задание"),
    "Dars": ("Lesson", "Урок"),
    "Darslar jurnali": ("Lesson journal", "Журнал уроков"),
    "%(n)s ta o'quvchi davomati saqlandi (%(day)s).": ("Attendance saved for %(n)s students (%(day)s).", "Посещаемость сохранена для %(n)s учеников (%(day)s)."),
    "Yanvar": ("January", "Январь"),
    "Fevral": ("February", "Февраль"),
    "Mart": ("March", "Март"),
    "Aprel": ("April", "Апрель"),
    "May": ("May", "Май"),
    "Iyun": ("June", "Июнь"),
    "Iyul": ("July", "Июль"),
    "Avgust": ("August", "Август"),
    "Sentabr": ("September", "Сентябрь"),
    "Oktabr": ("October", "Октябрь"),
    "Noyabr": ("November", "Ноябрь"),
    "Dekabr": ("December", "Декабрь"),
    "Baho qo'shildi.": ("Grade added.", "Оценка добавлена."),
    "Yangi baho": ("New grade", "Новая оценка"),
    "Baho o'chirildi.": ("Grade deleted.", "Оценка удалена."),
    "Dars qo'shildi.": ("Lesson added.", "Урок добавлен."),
    # --- payments ---
    "Yil": ("Year", "Год"),
    "Oy": ("Month", "Месяц"),
    "To'lov muddati (oyning kuni)": ("Due date (day of month)", "Срок оплаты (день месяца)"),
    "To'lanmagan": ("Unpaid", "Не оплачено"),
    "Qisman to'langan": ("Partially paid", "Частично оплачено"),
    "To'langan": ("Paid", "Оплачено"),
    "Summa": ("Amount", "Сумма"),
    "To'lov muddati": ("Due date", "Срок оплаты"),
    "Hisob-faktura": ("Invoice", "Счёт"),
    "Hisob-fakturalar": ("Invoices", "Счета"),
    "Naqd": ("Cash", "Наличные"),
    "Plastik karta": ("Card", "Банковская карта"),
    "Click": ("Click", "Click"),
    "Payme": ("Payme", "Payme"),
    "Bank o'tkazmasi": ("Bank transfer", "Банковский перевод"),
    "To'lov turi": ("Payment method", "Способ оплаты"),
    "To'lov vaqti": ("Payment time", "Время оплаты"),
    "Qabul qildi": ("Received by", "Принял"),
    "To'lov": ("Payment", "Платёж"),
    "To'lovlar": ("Payments", "Платежи"),
    "%(amount)s so'm to'lov qabul qilindi.": ("Payment of %(amount)s soʻm received.", "Принят платёж на %(amount)s сум."),
    "To'lov qabul qilish": ("Accept payment", "Принять платёж"),
    "To'lov o'chirildi.": ("Payment deleted.", "Платёж удалён."),
    "Hisob-faktura yaratildi.": ("Invoice created.", "Счёт создан."),
    "Yangi hisob-faktura": ("New invoice", "Новый счёт"),
    "%(created)s ta hisob-faktura yaratildi. %(skipped)s ta allaqachon mavjud edi.": ("%(created)s invoices created. %(skipped)s already existed.", "Создано счетов: %(created)s. Уже существовало: %(skipped)s."),
    "Hisob-faktura o'chirildi.": ("Invoice deleted.", "Счёт удалён."),
    # --- salaries models ---
    "Menejer / Qabul": ("Manager / Reception", "Менеджер / Ресепшн"),
    "Yordamchi xodim": ("Support staff", "Вспомогательный персонал"),
    "Farrosh": ("Cleaner", "Уборщик"),
    "Qorovul": ("Guard", "Охранник"),
    "Belgilangan oylik": ("Fixed salary", "Фиксированный оклад"),
    "Soatbay": ("Hourly", "Почасовой"),
    "O'quvchi soniga qarab": ("Per student", "По числу учеников"),
    "Aralash (oylik + KPI)": ("Mixed (salary + KPI)", "Смешанный (оклад + KPI)"),
    "F.I.O.": ("Full name", "Ф.И.О."),
    "Ish turi": ("Employment type", "Тип занятости"),
    "Belgilangan oylik (so'm)": ("Fixed salary (soʻm)", "Фиксированный оклад (сум)"),
    "Soatlik stavka (so'm)": ("Hourly rate (soʻm)", "Почасовая ставка (сум)"),
    "Har bir o'quvchi uchun (so'm)": ("Per student (soʻm)", "За каждого ученика (сум)"),
    "KPI bonusi (oylikning %)": ("KPI bonus (% of salary)", "KPI-бонус (% от оклада)"),
    "Davomat va o'zlashtirishga qarab beriladigan maksimal bonus foizi.": ("Maximum bonus percentage based on attendance and performance.", "Максимальный процент бонуса в зависимости от посещаемости и успеваемости."),
    "Bitta kechikish jarimasi (so'm)": ("Penalty per lateness (soʻm)", "Штраф за одно опоздание (сум)"),
    "Ishga kirgan sana": ("Hire date", "Дата приёма на работу"),
    "Xodim": ("Employee", "Сотрудник"),
    "Xodimlar": ("Employees", "Сотрудники"),
    "Qoralama": ("Draft", "Черновик"),
    "Yopilgan": ("Closed", "Закрыт"),
    "Oylik davri": ("Salary period", "Период зарплаты"),
    "Oylik davrlari": ("Salary periods", "Периоды зарплаты"),
    "Hisoblandi": ("Computed", "Рассчитано"),
    "Tasdiqlandi": ("Approved", "Утверждено"),
    "To'landi": ("Paid", "Выплачено"),
    "Ishlagan kunlar": ("Days worked", "Отработанные дни"),
    "Ishlagan soatlar": ("Hours worked", "Отработанные часы"),
    "O'tilgan darslar": ("Lessons taught", "Проведённые уроки"),
    "Guruhlar soni": ("Number of groups", "Число групп"),
    "O'quvchilar soni": ("Number of students", "Число учеников"),
    "Davomat (%)": ("Attendance (%)", "Посещаемость (%)"),
    "O'rtacha o'zlashtirish (%)": ("Average performance (%)", "Средняя успеваемость (%)"),
    "Kechikishlar": ("Late arrivals", "Опоздания"),
    "Sababsiz kelmaslik": ("Unexcused absences", "Прогулы"),
    "Qo'shimcha bonus (so'm)": ("Extra bonus (soʻm)", "Дополнительный бонус (сум)"),
    "Qo'shimcha jarima (so'm)": ("Extra penalty (soʻm)", "Дополнительный штраф (сум)"),
    "Jami (so'm)": ("Total (soʻm)", "Итого (сум)"),
    "KPI ko'rsatkichi (0-100)": ("KPI score (0-100)", "Показатель KPI (0-100)"),
    "Tarkib": ("Breakdown", "Состав"),
    "AI tahlili": ("AI analysis", "AI-анализ"),
    "AI tavsiyasi": ("AI recommendation", "AI-рекомендация"),
    "AI bahosi": ("AI rating", "AI-оценка"),
    "AI ishlatildi": ("AI used", "AI использован"),
    "AI model": ("AI model", "AI-модель"),
    "Hisoblangan vaqt": ("Computed at", "Время расчёта"),
    "Oylik yozuvi": ("Salary record", "Запись зарплаты"),
    "Oylik yozuvlari": ("Salary records", "Записи зарплаты"),
    "%(period)s: %(created)s ta yangi hisoblandi, %(updated)s ta yangilandi.": ("%(period)s: %(created)s newly computed, %(updated)s updated.", "%(period)s: рассчитано новых — %(created)s, обновлено — %(updated)s."),
    "AI tahlili tayyor.": ("AI analysis is ready.", "AI-анализ готов."),
    "AI tahlili tuzildi (API kalitsiz, mahalliy rejim).": ("AI analysis created (no API key, local mode).", "AI-анализ создан (без API-ключа, локальный режим)."),
    "Avval oylikni hisoblang.": ("Compute the salary first.", "Сначала рассчитайте зарплату."),
    "%(n)s ta xodim Claude AI bilan tahlil qilindi.": ("%(n)s employees were analyzed with Claude AI.", "%(n)s сотрудников проанализированы с помощью Claude AI."),
    "%(n)s ta xodim mahalliy rejimda tahlil qilindi. Claude uchun ANTHROPIC_API_KEY ni .env ga qo'shing.": ("%(n)s employees were analyzed in local mode. Add ANTHROPIC_API_KEY to .env for Claude.", "%(n)s сотрудников проанализированы в локальном режиме. Для Claude добавьте ANTHROPIC_API_KEY в .env."),
    "Metrikalar saqlandi va oylik qayta hisoblandi.": ("Metrics saved and the salary recomputed.", "Метрики сохранены, зарплата пересчитана."),
    "Metrikalar monitoring ma'lumotlaridan yangilandi.": ("Metrics updated from monitoring data.", "Метрики обновлены из данных мониторинга."),
    "Holat yangilandi: %(status)s.": ("Status updated: %(status)s.", "Статус обновлён: %(status)s."),
    "Xodim qo'shildi.": ("Employee added.", "Сотрудник добавлен."),
    "Xodim ma'lumotlari yangilandi.": ("Employee details updated.", "Данные сотрудника обновлены."),
    "Xodim o'chirildi.": ("Employee deleted.", "Сотрудник удалён."),
    "%(n)s ta xodim foydalanuvchilardan qo'shildi.": ("%(n)s employees were added from users.", "%(n)s сотрудников добавлены из пользователей."),
    "Yangi xodim topilmadi — barchasi allaqachon mavjud.": ("No new employees found — all already exist.", "Новых сотрудников не найдено — все уже существуют."),
    # --- students models ---
    "O'g'il bola": ("Boy", "Мальчик"),
    "Qiz bola": ("Girl", "Девочка"),
    "Bitirgan": ("Graduated", "Окончил"),
    "Tark etgan": ("Left", "Покинул"),
    "Otasining ismi": ("Middle name", "Отчество"),
    "Jinsi": ("Gender", "Пол"),
    "Tug'ilgan sana": ("Birth date", "Дата рождения"),
    "Manzil": ("Address", "Адрес"),
    "Maktab": ("School", "Школа"),
    "Sinf": ("Grade", "Класс"),
    "Balans (so'm)": ("Balance (soʻm)", "Баланс (сум)"),
    "Manfiy = qarzdor": ("Negative = in debt", "Отрицательный = задолженность"),
    "O'quvchi bot orqali ro'yxatdan o'tganda to'ldiriladi (bot xabar yuborish uchun).": ("Filled when the student registers via the bot (for the bot to send messages).", "Заполняется при регистрации ученика через бот (для отправки сообщений ботом)."),
    "O'quvchilar": ("Students", "Ученики"),
    # --- students/views.py ---
    "yaratildi": ("created", "создан"),
    "yangilandi": ("updated", "обновлён"),
    "Kabinet logini %(action)s. Login va parol o'quvchining Telegram'iga yuborildi. Login: %(username)s · Parol: %(password)s": ("Cabinet login %(action)s. Login and password sent to the student's Telegram. Login: %(username)s · Password: %(password)s", "Логин кабинета %(action)s. Логин и пароль отправлены в Telegram ученика. Логин: %(username)s · Пароль: %(password)s"),
    "Kabinet logini %(action)s. Login: %(username)s · Parol: %(password)s (Telegram ulanmagani uchun bu ma'lumotni o'quvchiga o'zingiz yetkazing).": ("Cabinet login %(action)s. Login: %(username)s · Password: %(password)s (Telegram is not linked, so deliver this info to the student yourself).", "Логин кабинета %(action)s. Логин: %(username)s · Пароль: %(password)s (Telegram не подключён, передайте данные ученику сами)."),
    "%(name)s qo'shildi. Login (%(username)s) va parol o'quvchining Telegram'iga yuborildi.": ("%(name)s added. Login (%(username)s) and password sent to the student's Telegram.", "%(name)s добавлен. Логин (%(username)s) и пароль отправлены в Telegram ученика."),
    "%(name)s qo'shildi. Kabinet logini — Login: %(username)s · Parol: %(password)s (bu ma'lumotni o'quvchiga yetkazing).": ("%(name)s added. Cabinet login — Login: %(username)s · Password: %(password)s (deliver this info to the student).", "%(name)s добавлен. Логин кабинета — Логин: %(username)s · Пароль: %(password)s (передайте данные ученику)."),
    "%(name)s qo'shildi.": ("%(name)s added.", "%(name)s добавлен."),
    "Yangi o'quvchi": ("New student", "Новый ученик"),
    "Ma'lumotlar yangilandi.": ("Details updated.", "Данные обновлены."),
    "O'quvchi o'chirildi.": ("Student deleted.", "Ученик удалён."),
    # --- accounts/_user_table.html ---
    "Amallar": ("Actions", "Действия"),
    "Ko‘rsatish": ("Show", "Показать"),
    "O‘chiq": ("Off", "Выключен"),
    "Tahrirlash": ("Edit", "Редактировать"),
    "Parol almashtirish": ("Change password", "Сменить пароль"),
    "Sahifasiga kirish": ("Open account", "Войти в учётную запись"),
    "O‘chirish": ("Delete", "Удалить"),
    "Hozircha yo‘q": ("None yet", "Пока нет"),
    # --- auth_base.html / login.html / register.html ---
    "Kirish": ("Sign in", "Вход"),
    "O'quv Markazi CRM": ("Learning Center CRM", "CRM учебного центра"),
    "Onlayn ro'yxat, to'lovlar boshqaruvi, o'quv jarayoni monitoringi va xodimlar oyligini sun'iy intellekt bilan hisoblashning yagona professional tizimi.": ("A single professional system for online enrollment, payment management, learning-process monitoring and AI-powered staff salary calculation.", "Единая профессиональная система онлайн-записи, управления платежами, мониторинга учебного процесса и расчёта зарплаты сотрудников с помощью ИИ."),
    "Rolga asoslangan xavfsiz kirish": ("Secure role-based access", "Безопасный вход на основе ролей"),
    "To'lovlar va qarzdorlik monitoringi": ("Payments and debt monitoring", "Мониторинг платежей и задолженностей"),
    "Davomat, baholar va reyting": ("Attendance, grades and ranking", "Посещаемость, оценки и рейтинг"),
    "AI bilan oylik hisoblash": ("AI-powered salary calculation", "Расчёт зарплаты с помощью ИИ"),
    "barcha huquqlar himoyalangan": ("all rights reserved", "все права защищены"),
    "Xavfsiz kirish": ("Secure access", "Безопасный вход"),
    "Tizimga kirish": ("Sign in to the system", "Вход в систему"),
    "Yangi parol o'rnating": ("Set a new password", "Установите новый пароль"),
    "Xavfsizlik uchun yangi parol yarating. Parolni ikki marta kiriting — keyin shu parol bilan tizimga kirasiz.": ("Create a new password for security. Enter it twice — you'll sign in with it afterwards.", "Создайте новый пароль для безопасности. Введите его дважды — затем вы будете входить с ним."),
    "Parolni saqlash": ("Save password", "Сохранить пароль"),
    "Bekor qilib chiqish": ("Cancel and sign out", "Отменить и выйти"),
    "Rolingizni tanlang, so'ng login va parolingiz bilan kiring.": ("Select your role, then sign in with your login and password.", "Выберите свою роль, затем войдите по логину и паролю."),
    "Kim sifatida kirasiz?": ("Sign in as?", "Войти как?"),
    "To'liq tizim nazorati": ("Full system control", "Полный контроль над системой"),
    "Boshqaruv va monitoring": ("Management and monitoring", "Управление и мониторинг"),
    "Davomat, baholar, oylik": ("Attendance, grades, salary", "Посещаемость, оценки, зарплата"),
    "Baholar, davomat, to'lovlar": ("Grades, attendance, payments", "Оценки, посещаемость, платежи"),
    "Parolni unutdingizmi?": ("Forgot your password?", "Забыли пароль?"),
    "Administrator yoki direktor hisobi kerakmi?": ("Need an administrator or director account?", "Нужна учётная запись администратора или директора?"),
    "O'qituvchi yoki o'quvchimisiz? Parolni tiklash": ("Are you a teacher or student? Reset password", "Вы преподаватель или ученик? Сбросить пароль"),
    "Mening profilim": ("My profile", "Мой профиль"),
    "Ro'yxatdan o'tgan": ("Registered", "Зарегистрирован"),
    "Ma'lumotlarni tahrirlash": ("Edit details", "Редактировать данные"),
    "Saqlash": ("Save", "Сохранить"),
    "Chiqish": ("Sign out", "Выйти"),
    "Faqat <b>Administrator</b> va <b>Direktor</b> o'zini ro'yxatdan o'tkaza oladi. Tasdiqlash kodi siz tanlagan usul — <b>Telegram bot</b> yoki <b>Gmail</b> — orqali yuboriladi.": ("Only an <b>Administrator</b> and <b>Director</b> can self-register. The verification code is sent via the method you choose — <b>Telegram bot</b> or <b>Gmail</b>.", "Зарегистрироваться могут только <b>Администратор</b> и <b>Директор</b>. Код подтверждения отправляется выбранным способом — через <b>Telegram-бот</b> или <b>Gmail</b>."),
    "Lavozimni tanlang": ("Choose a role", "Выберите должность"),
    "Telegram botni oching, <b>«🆔 ID raqamim»</b> tugmasini bosing va chiqqan raqamni quyiga kiriting.": ("Open the Telegram bot, tap <b>«🆔 My ID»</b> and enter the shown number below.", "Откройте Telegram-бот, нажмите <b>«🆔 Мой ID»</b> и введите показанный номер ниже."),
    "6 xonali tasdiqlash kodi shu manzilga yuboriladi.": ("A 6-digit verification code will be sent to this address.", "6-значный код подтверждения будет отправлен на этот адрес."),
    "Botga kod yuborish": ("Send code to bot", "Отправить код в бот"),
    "Hozircha yangi Administrator yoki Direktor uchun bo'sh joy yo'q. O'qituvchi va o'quvchilarni Administrator yaratadi.": ("There are currently no free slots for a new Administrator or Director. Teachers and students are created by the Administrator.", "Сейчас нет свободных мест для нового Администратора или Директора. Преподавателей и учеников создаёт Администратор."),
    "Hisobingiz bormi?": ("Already have an account?", "Уже есть учётная запись?"),
    # --- reset_help.html ---
    "O'qituvchi va o'quvchilar parolni Telegram bot orqali administratordan tiklaydi.": ("Teachers and students reset their password from the administrator via the Telegram bot.", "Преподаватели и ученики сбрасывают пароль через Telegram-бот у администратора."),
    "Telegram botni oching": ("Open the Telegram bot", "Откройте Telegram-бот"),
    "Quyidagi tugma orqali markaz botiga o'ting.": ("Go to the center's bot using the button below.", "Перейдите в бот центра по кнопке ниже."),
    "<b>«🔑 Parolni tiklash»</b> tugmasini bosing": ("Tap the <b>«🔑 Reset password»</b> button", "Нажмите кнопку <b>«🔑 Сбросить пароль»</b>"),
    "So'ng <b>O'qituvchi</b> yoki <b>O'quvchi</b> ni tanlang.": ("Then choose <b>Teacher</b> or <b>Student</b>.", "Затем выберите <b>Преподаватель</b> или <b>Ученик</b>."),
    "<b>«Adminga murojaat»</b> ni bosing": ("Tap <b>«Contact admin»</b>", "Нажмите <b>«Обращение к админу»</b>"),
    "Murojaat administratorga tushadi.": ("The request goes to the administrator.", "Обращение поступит администратору."),
    "Yangi parolni kuting": ("Wait for the new password", "Дождитесь нового пароля"),
    "Administrator yangi parol o'rnatadi va bot sizga yuboradi.": ("The administrator sets a new password and the bot sends it to you.", "Администратор установит новый пароль, и бот отправит его вам."),
    "Telegram botni ochish": ("Open Telegram bot", "Открыть Telegram-бот"),
    "Markaz Telegram boti administrator tomonidan ulanadi.": ("The center's Telegram bot is connected by the administrator.", "Telegram-бот центра подключается администратором."),
    "Kirish sahifasiga qaytish": ("Back to sign-in page", "Вернуться на страницу входа"),
    # --- reset_requests.html ---
    "O'qituvchi va o'quvchilar Telegram bot orqali yuborgan murojaatlar": ("Requests sent by teachers and students via the Telegram bot", "Обращения, отправленные преподавателями и учениками через Telegram-бот"),
    "Yangi murojaatlar": ("New requests", "Новые обращения"),
    "Login/tel": ("Login/phone", "Логин/тел"),
    "Topildi": ("Found", "Найдено"),
    "Avto-topilmadi — login kiriting": ("Not auto-found — enter login", "Не найдено автоматически — введите логин"),
    "Tasodifiy parol": ("Random password", "Случайный пароль"),
    "Saqlash + yuborish": ("Save + send", "Сохранить + отправить"),
    "Murojaatni rad etasizmi?": ("Reject this request?", "Отклонить обращение?"),
    "Yangi murojaat yo'q": ("No new requests", "Нет новых обращений"),
    "Tarix": ("History", "История"),
    "Tarix bo'sh": ("History is empty", "История пуста"),
    # --- settings.html ---
    "Sozlamalar": ("Settings", "Настройки"),
    "Hisobingiz, markaz ma'lumotlari va foydalanuvchilar loginlari": ("Your account, center details and user logins", "Ваша учётная запись, данные центра и логины пользователей"),
    "Hisob & Parol": ("Account & Password", "Аккаунт и пароль"),
    "Markaz ma'lumotlari": ("Center details", "Данные центра"),
    "Direktor & Admin": ("Director & Admin", "Директор и Админ"),
    "Mening hisobim": ("My account", "Моя учётная запись"),
    "Rasm yuklash": ("Upload photo", "Загрузить фото"),
    "Profilni tahrirlash": ("Edit profile", "Редактировать профиль"),
    "Parolni o'zgartirish": ("Change password", "Изменить пароль"),
    "O'quv markazi ma'lumotlari": ("Learning center details", "Данные учебного центра"),
    "Sayt, bot va cheklarda ishlatiladi": ("Used on the site, bot and receipts", "Используется на сайте, в боте и чеках"),
    "Markaz nomi": ("Center name", "Название центра"),
    "Shior": ("Tagline", "Слоган"),
    "Ish vaqti": ("Working hours", "Рабочее время"),
    "Telegram bot (@siz)": ("Telegram bot (without @)", "Telegram-бот (без @)"),
    "Logo": ("Logo", "Логотип"),
    "Markaz haqida": ("About the center", "О центре"),
    "login va parollar": ("logins and passwords", "логины и пароли"),
    "To'liq ro'yxat": ("Full list", "Полный список"),
    "Direktorlar": ("Directors", "Директора"),
    "Administratorlar": ("Administrators", "Администраторы"),
    # --- user_form.html ---
    "Yangi foydalanuvchi": ("New user", "Новый пользователь"),
    "O'qituvchi, o'quvchi, direktor yoki administrator hisobini boshqaring": ("Manage a teacher, student, director or administrator account", "Управляйте учётной записью преподавателя, ученика, директора или администратора"),
    "Orqaga": ("Back", "Назад"),
    "Faol hisob": ("Active account", "Активная учётная запись"),
    "Bekor qilish": ("Cancel", "Отмена"),
    # --- users_list.html ---
    "Barcha hisoblar — login va parollar, tahrirlash, hisobiga kirish": ("All accounts — logins and passwords, editing, sign-in", "Все учётные записи — логины и пароли, редактирование, вход"),
    "Hammasi": ("All", "Все"),
    "Login, ism, telefon...": ("Login, name, phone...", "Логин, имя, телефон..."),
    "Qidirish": ("Search", "Поиск"),
    "Hisobiga kirish": ("Sign in to account", "Войти в учётную запись"),
    "Foydalanuvchi topilmadi": ("No users found", "Пользователи не найдены"),
    "Yangi parol kiriting (bo‘sh = tasodifiy):": ("Enter a new password (empty = random):", "Введите новый пароль (пусто = случайный):"),
    "foydalanuvchini o‘chirasizmi?": ("delete this user?", "удалить пользователя?"),
    # --- base.html ---
    "Siz <b>%(name)s</b> (%(role)s) hisobini ko'ryapsiz": ("You are viewing the <b>%(name)s</b> (%(role)s) account", "Вы просматриваете учётную запись <b>%(name)s</b> (%(role)s)"),
    "Admin hisobiga qaytish": ("Back to admin account", "Вернуться в учётную запись администратора"),
    # --- cabinet base/overview ---
    "Mening kabinetim": ("My cabinet", "Мой кабинет"),
    "O'quvchi kabineti": ("Student cabinet", "Кабинет ученика"),
    "Til": ("Language", "Язык"),
    "Tungi/kunduzgi rejim": ("Dark/light mode", "Тёмный/светлый режим"),
    "Admin ko'rinishi": ("Admin view", "Просмотр администратора"),
    "Profil": ("Profile", "Профиль"),
    "<b>Admin ko'rinishi.</b> Siz <b>%(name)s</b> o'quvchining shaxsiy kabinetini ko'rib turibsiz.": ("<b>Admin view.</b> You are viewing the personal cabinet of student <b>%(name)s</b>.", "<b>Просмотр администратора.</b> Вы просматриваете личный кабинет ученика <b>%(name)s</b>."),
    "o'quvchi shaxsiy kabineti": ("student's personal cabinet", "личный кабинет ученика"),
    "Hisob hali bog'lanmagan": ("Account not linked yet", "Учётная запись ещё не связана"),
    "Sizning foydalanuvchi hisobingiz hali o'quvchi profiliga bog'lanmagan. Iltimos, markaz ma'muriyatiga murojaat qiling.": ("Your user account is not linked to a student profile yet. Please contact the center administration.", "Ваша учётная запись ещё не связана с профилем ученика. Пожалуйста, обратитесь в администрацию центра."),
    "Assalomu alaykum, %(name)s! 👋": ("Hello, %(name)s! 👋", "Здравствуйте, %(name)s! 👋"),
    "Bu sizning shaxsiy kabinetingiz — kurslaringiz, baholaringiz va to'lovlaringizni shu yerda kuzating.": ("This is your personal cabinet — track your courses, grades and payments here.", "Это ваш личный кабинет — следите здесь за курсами, оценками и платежами."),
    "O'zlashtirish": ("Performance", "Успеваемость"),
    "Qarz: %(amount)s so'm": ("Debt: %(amount)s soʻm", "Долг: %(amount)s сум"),
    "To'lovlar joyida": ("Payments up to date", "Платежи в порядке"),
    "O'rtacha baho": ("Average grade", "Средний балл"),
    "Faol kurslar": ("Active courses", "Активные курсы"),
    "Jami %(n)s ta yozilish": ("%(n)s enrollments in total", "Всего зачислений: %(n)s"),
    "Balans": ("Balance", "Баланс"),
    "so'm": ("soʻm", "сум"),
    "qarzdorlik": ("debt", "задолженность"),
    "Fanlar bo'yicha o'zlashtirish (%%)": ("Performance by subject (%%)", "Успеваемость по предметам (%%)"),
    "Hali baholar mavjud emas": ("No grades yet", "Оценок пока нет"),
    "Baholar taqsimoti": ("Grade distribution", "Распределение оценок"),
    "%(n)s ta": ("%(n)s", "%(n)s"),
    "Guruhdagi reytingim": ("My ranking in the group", "Мой рейтинг в группе"),
    "Guruhdoshlar orasida o'zlashtirish bo'yicha o'rin": ("Position by performance among groupmates", "Место по успеваемости среди одногруппников"),
    "<b>%(rank)s</b>-o'rin / %(total)s o'quvchi": ("place <b>%(rank)s</b> / %(total)s students", "<b>%(rank)s</b>-е место / %(total)s учеников"),
    "Reyting yo'q": ("No ranking", "Нет рейтинга"),
    "o'rtacha": ("average", "в среднем"),
    "Mening kurslarim va jadvalim": ("My courses and schedule", "Мои курсы и расписание"),
    "%(fee)s so'm/oy": ("%(fee)s soʻm/month", "%(fee)s сум/мес"),
    "Siz hali birorta kursga yozilmagansiz": ("You are not enrolled in any course yet", "Вы пока не записаны ни на один курс"),
    "To'lovlarim": ("My payments", "Мои платежи"),
    "Jami to'langan: <b>%(paid)s</b> so'm": ("Total paid: <b>%(paid)s</b> soʻm", "Всего оплачено: <b>%(paid)s</b> сум"),
    "Oy / Kurs": ("Month / Course", "Месяц / Курс"),
    "Qisman": ("Partial", "Частично"),
    "Bekor": ("Cancelled", "Отменён"),
    "Chek (PDF)": ("Receipt (PDF)", "Чек (PDF)"),
    "Chek": ("Receipt", "Чек"),
    "Hisob-fakturalar yo'q": ("No invoices", "Нет счетов"),
    "So'nggi baholar": ("Recent grades", "Последние оценки"),
    "%(n)s ta baho": ("%(n)s grades", "Оценок: %(n)s"),
    "Sana / Fan": ("Date / Subject", "Дата / Предмет"),
    "Natija": ("Result", "Результат"),
    "Hali baholar yo'q": ("No grades yet", "Оценок пока нет"),
    "A'lo (5)": ("Excellent (5)", "Отлично (5)"),
    "Yaxshi (4)": ("Good (4)", "Хорошо (4)"),
    "Qoniqarli (3)": ("Satisfactory (3)", "Удовлетворительно (3)"),
    "Past (2)": ("Low (2)", "Низко (2)"),
    # --- courses templates ---
    "Tahrir": ("Edit", "Изм."),
    "Davomiyligi": ("Duration", "Длительность"),
    "%(n)s oy": ("%(n)s months", "%(n)s мес."),
    "Bo'sh joy": ("Free seats", "Свободных мест"),
    "O'quvchilar ro'yxati": ("Student list", "Список учеников"),
    "O'quvchi yozish": ("Enroll a student", "Записать ученика"),
    "Boshlangan": ("Started", "Начато"),
    "Bu guruhda hali o'quvchi yo'q": ("No students in this group yet", "В этой группе пока нет учеников"),
    "O'quv guruhlari": ("Study groups", "Учебные группы"),
    "Barcha guruhlar va ularning to'ldirilishi": ("All groups and their occupancy", "Все группы и их заполненность"),
    "Guruh yoki yo'nalish...": ("Group or subject...", "Группа или направление..."),
    "Barcha yo'nalish": ("All subjects", "Все направления"),
    "Barcha holat": ("All statuses", "Все статусы"),
    "Filtr": ("Filter", "Фильтр"),
    "O'qituvchi tayinlanmagan": ("No teacher assigned", "Преподаватель не назначен"),
    "%(fee)s so'm / oy": ("%(fee)s soʻm / month", "%(fee)s сум / мес"),
    "To'ldirilgan": ("Filled", "Заполнено"),
    "Guruh topilmadi.": ("No groups found.", "Группы не найдены."),
    "Yangi guruh qo'shing": ("Add a new group", "Добавьте новую группу"),
    "O'quv yo'nalishlari": ("Study subjects", "Учебные направления"),
    "Fanlar va yo'nalishlar ro'yxati": ("List of subjects and directions", "Список предметов и направлений"),
    "%(n)s ta guruh": ("%(n)s groups", "Групп: %(n)s"),
    "Nofaol": ("Inactive", "Неактивен"),
    "Yo'nalish yo'q.": ("No subjects.", "Нет направлений."),
    "Birinchisini qo'shing": ("Add the first one", "Добавьте первое"),
    # --- dashboard director/home ---
    "Direktor paneli": ("Director panel", "Панель директора"),
    "Salom, %(name)s! 👋": ("Hello, %(name)s! 👋", "Здравствуйте, %(name)s! 👋"),
    "%(brand)s — boshqaruv va monitoring": ("%(brand)s — management and monitoring", "%(brand)s — управление и мониторинг"),
    "O'quv jarayoni": ("Learning process", "Учебный процесс"),
    "Faol o'quvchilar": ("Active students", "Активные ученики"),
    "Jami %(total)s ta": ("%(total)s in total", "Всего: %(total)s"),
    "Shu oy tushum": ("This month's revenue", "Доход за этот месяц"),
    "so'm — joriy oy": ("soʻm — current month", "сум — текущий месяц"),
    "Qarzdorlik": ("Debt", "Задолженность"),
    "%(n)s ta qarzdor": ("%(n)s debtors", "Должников: %(n)s"),
    "Davomat (hafta)": ("Attendance (week)", "Посещаемость (неделя)"),
    "O'rtacha baho %(score)s%%": ("Average grade %(score)s%%", "Средний балл %(score)s%%"),
    "Faol guruhlar soni": ("Number of active groups", "Число активных групп"),
    "Faol o'qituvchilar": ("Active teachers", "Активные преподаватели"),
    "Yangi arizalar": ("New applications", "Новые заявки"),
    "%(n)s ta ko'rilmagan": ("%(n)s unreviewed", "Не просмотрено: %(n)s"),
    "To'lov yig'ilishi": ("Collection rate", "Собираемость платежей"),
    "%(n)s to'lanmagan hisob": ("%(n)s unpaid invoices", "Неоплаченных счетов: %(n)s"),
    "Oxirgi 6 oy tushumi": ("Revenue for the last 6 months", "Доход за последние 6 месяцев"),
    "Yo'nalishlar bo'yicha o'quvchilar": ("Students by subject", "Ученики по направлениям"),
    "O'qituvchilar (o'quv jarayoni)": ("Teachers (learning process)", "Преподаватели (учебный процесс)"),
    "Barchasi": ("All", "Все"),
    "%(n)s guruh": ("%(n)s groups", "Групп: %(n)s"),
    "O'qituvchilar yo'q": ("No teachers", "Нет преподавателей"),
    "Eng katta qarzdorlar": ("Top debtors", "Крупнейшие должники"),
    "Qarzdorlar yo'q": ("No debtors", "Нет должников"),
    "Guruhlar to'ldirilganligi": ("Group occupancy", "Заполненность групп"),
    "Guruhlar yo'q": ("No groups", "Нет групп"),
    "Eng yaxshi o'zlashtirgan o'quvchilar": ("Top-performing students", "Лучшие по успеваемости ученики"),
    "Baholar yo'q": ("No grades", "Нет оценок"),
    "So'nggi to'lovlar": ("Recent payments", "Последние платежи"),
    "Moliya": ("Finance", "Финансы"),
    "To'lovlar yo'q": ("No payments", "Нет платежей"),
    "Boshqaruv paneli": ("Dashboard", "Панель управления"),
    "%(brand)s o'quv markazi — umumiy holat": ("%(brand)s learning center — overview", "Учебный центр %(brand)s — общая картина"),
    "Arizalar": ("Applications", "Заявки"),
    "Jami %(total)s ta ro'yxatda": ("%(total)s enrolled in total", "Всего в списке: %(total)s"),
    "%(n)s ta qarzdor o'quvchi": ("%(n)s students in debt", "Учеников с долгом: %(n)s"),
    "Bu oy %(n)s ta keldi": ("%(n)s came this month", "В этом месяце пришло: %(n)s"),
    "Faol guruhlar": ("Active groups", "Активные группы"),
    "Arizalar holati (funnel)": ("Application status (funnel)", "Статусы заявок (воронка)"),
    "So'nggi arizalar": ("Recent applications", "Последние заявки"),
    "Hozircha ariza yo'q": ("No applications yet", "Заявок пока нет"),
    "Hozircha to'lov yo'q": ("No payments yet", "Платежей пока нет"),
    "Qarz (so'm)": ("Debt (soʻm)", "Долг (сум)"),
    # --- dashboard/teacher.html ---
    "O'qituvchi paneli": ("Teacher panel", "Панель преподавателя"),
    "siz <b>%(name)s</b> o'qituvchi panelini ko'rib turibsiz.": ("you are viewing <b>%(name)s</b>'s teacher panel.", "вы просматриваете панель преподавателя <b>%(name)s</b>."),
    "Profilga qaytish": ("Back to profile", "Вернуться в профиль"),
    "Guruhlaringiz, jadvalingiz, davomat va baholar": ("Your groups, schedule, attendance and grades", "Ваши группы, расписание, посещаемость и оценки"),
    "Guruhlarim": ("My groups", "Мои группы"),
    "faol guruhlar": ("active groups", "активные группы"),
    "O'quvchilarim": ("My students", "Мои ученики"),
    "jami faol": ("total active", "всего активных"),
    "Oyligim": ("My salary", "Моя зарплата"),
    "batafsil": ("details", "подробнее"),
    "belgilanmagan": ("not set", "не указано"),
    "Bugungi darslarim": ("Today's lessons", "Мои уроки на сегодня"),
    "o'quvchi": ("students", "ученики"),
    "Davomat olish": ("Take attendance", "Отметить посещаемость"),
    "Bugun darsingiz yo'q. Dam oling!": ("No lessons today. Relax!", "Сегодня уроков нет. Отдыхайте!"),
    "Haftalik jadvalim": ("My weekly schedule", "Моё расписание на неделю"),
    "bugun": ("today", "сегодня"),
    "Jadval hali tuzilmagan.": ("The schedule is not set yet.", "Расписание ещё не составлено."),
    "Mening guruhlarim": ("My groups", "Мои группы"),
    "Sizga hali guruh biriktirilmagan. Administratorga murojaat qiling.": ("No group is assigned to you yet. Contact the administrator.", "Вам пока не назначена группа. Обратитесь к администратору."),
    # --- enrollments templates ---
    "O'quvchiga aylantirish": ("Convert to student", "Преобразовать в ученика"),
    "Arizani o'quvchiga aylantirish": ("Convert the application to a student", "Преобразовать заявку в ученика"),
    "Quyidagi ariza asosida yangi o'quvchi profili yaratiladi:": ("A new student profile will be created from the application below:", "На основе заявки ниже будет создан новый профиль ученика:"),
    "%(course)s guruhiga yoziladi": ("will be enrolled in the %(course)s group", "будет записан в группу %(course)s"),
    "Tasdiqlash": ("Confirm", "Подтвердить"),
    "Ariza — %(name)s": ("Application — %(name)s", "Заявка — %(name)s"),
    "O'quvchini ko'rish": ("View student", "Посмотреть ученика"),
    "Ariza ma'lumotlari": ("Application details", "Данные заявки"),
    "Ota-ona tel.": ("Parent's phone", "Тел. родителя"),
    "Manba": ("Source", "Источник"),
    "Xabar": ("Message", "Сообщение"),
    "Holatni boshqarish": ("Manage status", "Управление статусом"),
    "Potensial o'quvchilar — lead funnel boshqaruvi": ("Potential students — lead funnel management", "Потенциальные ученики — управление воронкой лидов"),
    "Ommaviy forma": ("Public form", "Публичная форма"),
    "Ism yoki telefon...": ("Name or phone...", "Имя или телефон..."),
    "Ko'rish": ("View", "Просмотр"),
    "Ariza topilmadi": ("No applications found", "Заявки не найдены"),
    "Onlayn ro'yxatdan o'tish": ("Online registration", "Онлайн-регистрация"),
    "%(BRAND_NAME)s o'quv markazi": ("%(BRAND_NAME)s learning center", "Учебный центр %(BRAND_NAME)s"),
    "Bilim sari birinchi qadam! Quyidagi shaklni to'ldiring — administratorlarimiz siz bilan tez orada bog'lanadi.": ("The first step toward knowledge! Fill out the form below — our administrators will contact you soon.", "Первый шаг к знаниям! Заполните форму ниже — наши администраторы скоро свяжутся с вами."),
    "Tajribali o'qituvchilar": ("Experienced teachers", "Опытные преподаватели"),
    "Zamonaviy metodika": ("Modern methodology", "Современная методика"),
    "Natijaga yo'naltirilgan": ("Result-oriented", "Ориентация на результат"),
    "Ro'yxatdan o'tish arizasi": ("Registration application", "Заявка на регистрацию"),
    "Barcha maydonlarni to'ldiring. Maxfiyligingiz kafolatlanadi.": ("Fill in all fields. Your privacy is guaranteed.", "Заполните все поля. Конфиденциальность гарантируется."),
    "Arizani yuborish": ("Submit application", "Отправить заявку"),
    "Allaqachon ro'yxatdan o'tganmisiz?": ("Already registered?", "Уже зарегистрированы?"),
    "Ariza qabul qilindi": ("Application received", "Заявка принята"),
    "Arizangiz qabul qilindi!": ("Your application has been received!", "Ваша заявка принята!"),
    "Rahmat! Tez orada administratorlarimiz siz bilan ko'rsatilgan telefon raqami orqali bog'lanadi.": ("Thank you! Our administrators will contact you soon using the phone number you provided.", "Спасибо! Наши администраторы скоро свяжутся с вами по указанному номеру телефона."),
    "Yana ariza qoldirish": ("Submit another application", "Оставить ещё одну заявку"),
    "%(n)s ta faol yozilish": ("%(n)s active enrollments", "Активных зачислений: %(n)s"),
    "Yozilish yo'q": ("No enrollments", "Нет зачислений"),
    # --- instructors templates ---
    "Panelini ko'rish": ("View panel", "Открыть панель"),
    "Tajriba": ("Experience", "Опыт"),
    "%(n)s yil": ("%(n)s years", "%(n)s лет"),
    "Yuritayotgan guruhlar": ("Groups taught", "Ведёт группы"),
    "%(n)s o'quvchi": ("%(n)s students", "Учеников: %(n)s"),
    "Guruh biriktirilmagan": ("No group assigned", "Группа не назначена"),
    "Yangi o'qituvchi": ("New teacher", "Новый преподаватель"),
    "Yangi o'qituvchi qo'shish": ("Add a new teacher", "Добавить нового преподавателя"),
    "Ma'lumotlarni to'ldiring — tizim avtomatik <b>o'qituvchi profili</b> va <b>kabinet logini</b> yaratadi.": ("Fill in the details — the system automatically creates a <b>teacher profile</b> and a <b>cabinet login</b>.", "Заполните данные — система автоматически создаст <b>профиль преподавателя</b> и <b>логин кабинета</b>."),
    "Shaxsiy ma'lumotlar": ("Personal details", "Личные данные"),
    "Kabinet logini (username / parol)": ("Cabinet login (username / password)", "Логин кабинета (username / пароль)"),
    "Bo'sh qoldirsangiz tizim unikal login tavsiya qiladi.": ("If left empty, the system suggests a unique login.", "Если оставить пустым, система предложит уникальный логин."),
    "Bo'sh — avtomatik xavfsiz parol. Login va parol bir marta ko'rsatiladi.": ("Empty — an automatic secure password. Login and password are shown once.", "Пусто — автоматический надёжный пароль. Логин и пароль показываются один раз."),
    "O'qituvchini saqlash": ("Save teacher", "Сохранить преподавателя"),
    "Markaz o'qituvchilari (%(active)s faol / %(total)s)": ("Center teachers (%(active)s active / %(total)s)", "Преподаватели центра (%(active)s активных / %(total)s)"),
    "%(n)s ta faol guruh": ("%(n)s active groups", "Активных групп: %(n)s"),
    "%(n)s yil tajriba": ("%(n)s years of experience", "%(n)s лет опыта"),
    "O'chirish": ("Delete", "Удалить"),
    "O'qituvchi yo'q.": ("No teachers.", "Нет преподавателей."),
    "Birinchi o'qituvchini qo'shing": ("Add the first teacher", "Добавьте первого преподавателя"),
    # --- monitoring templates ---
    "Davomat jurnali — %(name)s": ("Attendance journal — %(name)s", "Журнал посещаемости — %(name)s"),
    "Monitoring": ("Monitoring", "Мониторинг"),
    "Davomat jurnali": ("Attendance journal", "Журнал посещаемости"),
    "Bu oy uchun davomat yo'q": ("No attendance for this month", "Нет посещаемости за этот месяц"),
    "Davomat — %(name)s": ("Attendance — %(name)s", "Посещаемость — %(name)s"),
    "Jurnal": ("Journal", "Журнал"),
    "Hammasi keldi": ("All present", "Все пришли"),
    "Bu guruhda faol o'quvchi yo'q": ("No active students in this group", "В этой группе нет активных учеников"),
    "Davomatni saqlash": ("Save attendance", "Сохранить посещаемость"),
    "Baholar — %(name)s": ("Grades — %(name)s", "Оценки — %(name)s"),
    "Baholar jurnali": ("Grade journal", "Журнал оценок"),
    "Baho qo'shish": ("Add grade", "Добавить оценку"),
    "O'quvchilar reytingi": ("Student ranking", "Рейтинг учеников"),
    "O'quvchi yo'q": ("No students", "Нет учеников"),
    "O'quv monitoring": ("Learning monitoring", "Мониторинг обучения"),
    "O'quv jarayoni monitoringi": ("Learning process monitoring", "Мониторинг учебного процесса"),
    "Davomat, baholar va dars jurnallari bo'yicha nazorat": ("Control over attendance, grades and lesson journals", "Контроль посещаемости, оценок и журналов уроков"),
    "Davomat (7 kun)": ("Attendance (7 days)", "Посещаемость (7 дней)"),
    "Kelganlar": ("Present", "Пришедшие"),
    "Baholar (7 kun)": ("Grades (7 days)", "Оценки (7 дней)"),
    "Darslar (7 kun)": ("Lessons (7 days)", "Уроки (7 дней)"),
    "Guruhni tanlang": ("Select a group", "Выберите группу"),
    "Darslar": ("Lessons", "Уроки"),
    "Faol guruh yo'q.": ("No active groups.", "Нет активных групп."),
    "Guruh yarating": ("Create a group", "Создайте группу"),
    "Darslar jurnali — %(name)s": ("Lesson journal — %(name)s", "Журнал уроков — %(name)s"),
    "O'tilgan mavzular va uy vazifalari": ("Covered topics and homework", "Пройденные темы и домашние задания"),
    "Yangi dars qo'shish": ("Add a new lesson", "Добавить новый урок"),
    "Uy vazifa": ("Homework", "Домашнее задание"),
    "Hali dars kiritilmagan": ("No lessons recorded yet", "Уроки ещё не внесены"),
    "Hisobot — %(name)s": ("Report — %(name)s", "Отчёт — %(name)s"),
    "O'quvchi profili": ("Student profile", "Профиль ученика"),
    "O'quv hisoboti — %(name)s": ("Learning report — %(name)s", "Учебный отчёт — %(name)s"),
    "Umumiy davomat": ("Overall attendance", "Общая посещаемость"),
    "Guruhlar bo'yicha ko'rsatkichlar": ("Metrics by group", "Показатели по группам"),
    "Faol guruh yo'q": ("No active groups", "Нет активных групп"),
    "So'nggi davomat": ("Recent attendance", "Последняя посещаемость"),
    "Davomat yo'q": ("No attendance", "Нет посещаемости"),
    # --- sidebar ---
    "CRM Tizimi": ("CRM System", "CRM-система"),
    "Asosiy": ("Main", "Основное"),
    "Sahifalar": ("Pages", "Страницы"),
    "Moliya / To'lovlar": ("Finance / Payments", "Финансы / Платежи"),
    "Markaz": ("Center", "Центр"),
    "Oyliklar (AI)": ("Salaries (AI)", "Зарплаты (ИИ)"),
    "Ko'rinishlar": ("Views", "Виды"),
    "Boshqaruv": ("Administration", "Администрирование"),
    "Parol murojaatlari": ("Password requests", "Запросы пароля"),
    "Ommaviy ariza": ("Public application", "Публичная заявка"),
    "To'lovlar monitoringi": ("Payments monitoring", "Мониторинг платежей"),
    "Mening panelim": ("My panel", "Моя панель"),
    "Davomat va baholar": ("Attendance and grades", "Посещаемость и оценки"),
    "Mening oyligim": ("My salary", "Моя зарплата"),
    "Hisob": ("Account", "Аккаунт"),
    # --- payments templates ---
    "Qarzdorlar": ("Debtors", "Должники"),
    "Qarzdor o'quvchilar": ("Students in debt", "Ученики с задолженностью"),
    "Jami": ("Total", "Итого"),
    "Umumiy": ("Overview", "Общее"),
    "Qarz miqdori": ("Debt amount", "Сумма долга"),
    "Qarzdorlar yo'q — barcha to'lovlar joyida!": ("No debtors — all payments are up to date!", "Должников нет — все платежи в порядке!"),
    "Moliya boshqaruvi": ("Finance management", "Управление финансами"),
    "To'lovlar, hisob-fakturalar va qarzdorlik nazorati": ("Control of payments, invoices and debt", "Контроль платежей, счетов и задолженности"),
    "Oylik hisob-fakturalar": ("Monthly invoices", "Ежемесячные счета"),
    "%(n)s ta to'lov": ("%(n)s payments", "Платежей: %(n)s"),
    "Jami tushum": ("Total revenue", "Общий доход"),
    "Butun davr": ("Entire period", "За весь период"),
    "To'lanmagan faktura": ("Unpaid invoices", "Неоплаченные счета"),
    "To'lov yo'q": ("No payments", "Нет платежей"),
    "Qarz": ("Debt", "Долг"),
    "Tanlangan oy uchun barcha faol yozilishlarga avtomatik hisob-faktura yaratiladi.": ("Invoices are created automatically for all active enrollments for the selected month.", "Счета автоматически создаются для всех активных зачислений за выбранный месяц."),
    "Har bir faol o'quvchi uchun guruh oylik to'lovi (chegirma hisobga olingan holda) bo'yicha faktura yaratiladi. Takroriy fakturalar yaratilmaydi.": ("An invoice is created for each active student based on the group's monthly fee (with discount applied). Duplicate invoices are not created.", "Для каждого активного ученика создаётся счёт по ежемесячной оплате группы (с учётом скидки). Повторные счета не создаются."),
    "Fakturalarni yaratish": ("Generate invoices", "Создать счета"),
    "To'lanmagan jami": ("Total unpaid", "Всего не оплачено"),
    "Yangi faktura": ("New invoice", "Новый счёт"),
    "Oylik generatsiya": ("Monthly generation", "Месячная генерация"),
    "Muddati o'tgan": ("Overdue", "Просрочено"),
    "Davr": ("Period", "Период"),
    "Muddat": ("Due date", "Срок"),
    "To'lash": ("Pay", "Оплатить"),
    "Hisob-faktura yo'q.": ("No invoices.", "Нет счетов."),
    "Oylik generatsiya qiling": ("Generate monthly invoices", "Выполните месячную генерацию"),
    "To'lovlar tarixi": ("Payment history", "История платежей"),
    "Jami ko'rsatilgan": ("Total shown", "Всего показано"),
    "O'": ("O'", "O'"),
    "Barcha turi": ("All methods", "Все способы"),
    "To'lov topilmadi": ("No payments found", "Платежи не найдены"),
    "O'quvchi ismi...": ("Student name...", "Имя ученика..."),
    # --- salaries templates ---
    "Xodimni o'chirish": ("Delete employee", "Удалить сотрудника"),
    "<b>%(name)s</b> ni va unga tegishli barcha oylik yozuvlarini o'chirmoqchimisiz? Bu amalni qaytarib bo'lmaydi.": ("Delete <b>%(name)s</b> and all related salary records? This action cannot be undone.", "Удалить <b>%(name)s</b> и все связанные записи зарплаты? Это действие необратимо."),
    "Ha, o'chirish": ("Yes, delete", "Да, удалить"),
    "Yangi xodim": ("New employee", "Новый сотрудник"),
    "Xodimni tahrirlash": ("Edit employee", "Редактировать сотрудника"),
    "Yangi xodim qo'shish": ("Add a new employee", "Добавить нового сотрудника"),
    "Oylik turi va stavkalarni belgilang. KPI bonusi davomat va o'zlashtirishga qarab beriladi.": ("Set the salary type and rates. The KPI bonus depends on attendance and performance.", "Укажите тип зарплаты и ставки. KPI-бонус зависит от посещаемости и успеваемости."),
    "Oylik hisoblanadigan barcha xodimlar va ularning stavkalari. Faol: %(active)s": ("All employees with computed salaries and their rates. Active: %(active)s", "Все сотрудники с расчётной зарплатой и их ставки. Активных: %(active)s"),
    "Foydalanuvchilardan import": ("Import from users", "Импорт из пользователей"),
    "Oylik / stavka": ("Salary / rate", "Оклад / ставка"),
    "KPI %%": ("KPI %%", "KPI %%"),
    "soat": ("hour", "час"),
    "Hali xodim yo'q.": ("No employees yet.", "Сотрудников пока нет."),
    "Xodimlar oyligi — %(m)s %(y)s": ("Staff salary — %(m)s %(y)s", "Зарплата сотрудников — %(m)s %(y)s"),
    "Oylik suniy intellekt yordamida davomat, guruhlar va KPI asosida hisoblanadi.": ("Salaries are calculated by AI based on attendance, groups and KPI.", "Зарплата рассчитывается с помощью ИИ на основе посещаемости, групп и KPI."),
    "Ko'rsatish": ("Show", "Показать"),
    "Faol xodimlar": ("Active employees", "Активные сотрудники"),
    "Hisoblangan": ("Computed", "Рассчитано"),
    "AI tahlil qilingan": ("AI analyzed", "Проанализировано ИИ"),
    "Jami oylik fondi": ("Total salary fund", "Общий фонд зарплаты"),
    "Oylik jadvali": ("Salary table", "Таблица зарплат"),
    "Oylikni hisoblash": ("Compute salaries", "Рассчитать зарплату"),
    "AI bilan tahlil qilish": ("Analyze with AI", "Анализ с помощью ИИ"),
    "KPI": ("KPI", "KPI"),
    "Jami oylik": ("Total salary", "Итого зарплата"),
    "AI": ("AI", "ИИ"),
    "Batafsil": ("Details", "Подробнее"),
    "Hisoblanmagan": ("Not computed", "Не рассчитано"),
    "Xodim qo'shing": ("Add an employee", "Добавьте сотрудника"),
    "yoki foydalanuvchilardan import qiling.": ("or import from users.", "или импортируйте из пользователей."),
    "Hozir AI mahalliy (offline) rejimda ishlamoqda. To'liq Claude AI tahlili uchun <code>.env</code> fayliga <code>ANTHROPIC_API_KEY</code> ni qo'shing.": ("AI is currently running in local (offline) mode. For full Claude AI analysis, add <code>ANTHROPIC_API_KEY</code> to the <code>.env</code> file.", "Сейчас ИИ работает в локальном (офлайн) режиме. Для полного анализа Claude AI добавьте <code>ANTHROPIC_API_KEY</code> в файл <code>.env</code>."),
    "Hisob-varaqa": ("Payslip", "Расчётный лист"),
    "Chop etish": ("Print", "Печать"),
    "Oylik hisob-varaqasi": ("Salary payslip", "Расчётный лист зарплаты"),
    "Jami to'lov": ("Total payout", "Итого к выплате"),
    "JAMI": ("TOTAL", "ИТОГО"),
    "Karta": ("Card", "Карта"),
    "Oylik — %(name)s": ("Salary — %(name)s", "Зарплата — %(name)s"),
    "Metrikalar": ("Metrics", "Метрики"),
    "Avto yangilash": ("Auto refresh", "Автообновление"),
    "AI tahlil": ("AI analysis", "AI-анализ"),
    "Oylik tarkibi": ("Salary breakdown", "Состав зарплаты"),
    "KPI ko'rsatkichi": ("KPI score", "Показатель KPI"),
    "Holatni saqlash": ("Save status", "Сохранить статус"),
    "Davr ko'rsatkichlari": ("Period metrics", "Показатели за период"),
    "Ishlagan soat": ("Hours worked", "Отработано часов"),
    "Sababsiz": ("Unexcused", "Без причины"),
    "Suniy intellekt tahlili": ("AI analysis", "Анализ искусственного интеллекта"),
    "Tavsiya": ("Recommendation", "Рекомендация"),
    "✨ Claude AI (%(model)s)": ("✨ Claude AI (%(model)s)", "✨ Claude AI (%(model)s)"),
    "Mahalliy tahlil (API kalitsiz)": ("Local analysis (no API key)", "Локальный анализ (без API-ключа)"),
    "Hali tahlil qilinmagan. <b>AI tahlil</b> tugmasini bosing.": ("Not analyzed yet. Click the <b>AI analysis</b> button.", "Ещё не проанализировано. Нажмите кнопку <b>AI-анализ</b>."),
    "Jadvalga qaytish": ("Back to table", "Вернуться к таблице"),
    "Metrikalar — %(name)s": ("Metrics — %(name)s", "Метрики — %(name)s"),
    "Metrikalarni tahrirlash": ("Edit metrics", "Редактировать метрики"),
    "%(name)s · %(period)s. Saqlangach oylik avtomatik qayta hisoblanadi.": ("%(name)s · %(period)s. The salary is recomputed automatically after saving.", "%(name)s · %(period)s. После сохранения зарплата пересчитывается автоматически."),
    "Saqlash va qayta hisoblash": ("Save and recompute", "Сохранить и пересчитать"),
    # --- shared ---
    "O'chirishni tasdiqlash": ("Confirm deletion", "Подтверждение удаления"),
    "Rostdan o'chirilsinmi?": ("Really delete?", "Действительно удалить?"),
    "Ob'ekt": ("Object", "Объект"),
    "Forma": ("Form", "Форма"),
    "Ma'lumotlarni kiritish": ("Enter data", "Ввод данных"),
    # --- students/student_create.html ---
    "Yangi o'quvchi qo'shish": ("Add a new student", "Добавить нового ученика"),
    "Ma'lumotlarni to'ldiring va xohlasangiz darhol kabinet logini yarating.": ("Fill in the details and, if you wish, create a cabinet login right away.", "Заполните данные и при желании сразу создайте логин кабинета."),
    "O'quvchi uchun shaxsiy kabinet logini yaratilsin": ("Create a personal cabinet login for the student", "Создать личный логин кабинета для ученика"),
    "Username (login)": ("Username (login)", "Username (логин)"),
    "Bo'sh — avtomatik (ism+familiya)": ("Empty — automatic (first+last name)", "Пусто — автоматически (имя+фамилия)"),
    "Bo'sh qoldirsangiz tizim o'zi unikal login tavsiya qiladi.": ("If left empty, the system suggests a unique login.", "Если оставить пустым, система сама предложит уникальный логин."),
    "Telegram ulangan bo'lsa, login va parol botga yuboriladi.": ("If Telegram is linked, the login and password are sent to the bot.", "Если Telegram подключён, логин и пароль отправляются в бот."),
    # --- students/student_detail.html ---
    "Kabinet": ("Cabinet", "Кабинет"),
    "Hisobot": ("Report", "Отчёт"),
    "Guruhga yozish": ("Enroll in group", "Записать в группу"),
    "Qarzdor": ("In debt", "Должник"),
    "Joriy balans": ("Current balance", "Текущий баланс"),
    "Maktab / sinf": ("School / grade", "Школа / класс"),
    "O'quvchi kabineti (login)": ("Student cabinet (login)", "Кабинет ученика (логин)"),
    "Login mavjud": ("Login exists", "Логин есть"),
    "Telegram ulangan": ("Telegram linked", "Telegram подключён"),
    "Telegram ulanmagan": ("Telegram not linked", "Telegram не подключён"),
    "Parolni yangilash / qayta yuborish": ("Update / resend password", "Обновить / повторно отправить пароль"),
    "Bo'sh qoldirsangiz — avtomatik yaratiladi": ("If left empty — generated automatically", "Если оставить пустым — создаётся автоматически"),
    "Yangilash va yuborish": ("Update and send", "Обновить и отправить"),
    "O'quvchi uchun shaxsiy kabinet logini yarating. Telegram ulangan bo'lsa, login va parol avtomatik botga yuboriladi.": ("Create a personal cabinet login for the student. If Telegram is linked, the login and password are sent to the bot automatically.", "Создайте личный логин кабинета для ученика. Если Telegram подключён, логин и пароль отправляются в бот автоматически."),
    "Avtomatik yaratiladi": ("Generated automatically", "Создаётся автоматически"),
    "Login yaratish": ("Create login", "Создать логин"),
    "Guruhga yozilmagan": ("Not enrolled in any group", "Не записан ни в одну группу"),
    # --- students/student_list.html ---
    "Markazning barcha o'quvchilari": ("All students of the center", "Все ученики центра"),
    "Jami o'quvchi": ("Total students", "Всего учеников"),
    "O'quvchi topilmadi": ("No students found", "Ученики не найдены"),
}

# Maxsus: plural yozuv
PLURALS = {
    "%(counter)s yangi ariza": {
        "en": ["%(counter)s new application", "%(counter)s new applications"],
        "ru": ["%(counter)s новая заявка", "%(counter)s новые заявки", "%(counter)s новых заявок"],
    },
}


def apply(lang):
    path = f'locale/{lang}/LC_MESSAGES/django.po'
    po = polib.pofile(path)
    missing = []
    for e in po:
        if e.obsolete:
            continue
        if e.msgid_plural:
            data = PLURALS.get(e.msgid)
            if data:
                for i, val in enumerate(data[lang]):
                    e.msgstr_plural[i] = val
                if 'fuzzy' in e.flags:
                    e.flags.remove('fuzzy')
            else:
                missing.append(e.msgid)
            continue
        tr = T.get(e.msgid)
        if tr:
            e.msgstr = tr[0] if lang == 'en' else tr[1]
            if 'fuzzy' in e.flags:
                e.flags.remove('fuzzy')
        else:
            missing.append(e.msgid)
    po.save(path)
    return missing


for lang in ('en', 'ru'):
    miss = apply(lang)
    print(f'[{lang}] saved. missing={len(miss)}')
    for m in miss[:50]:
        print('   MISSING:', repr(m))
