# Generated by Django 6.0.4 on 2026-05-31 19:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O.')),
                ('position', models.CharField(choices=[('teacher', "O'qituvchi"), ('manager', 'Menejer / Qabul'), ('admin', 'Administrator'), ('support', 'Yordamchi xodim'), ('cleaner', 'Farrosh'), ('guard', 'Qorovul'), ('other', 'Boshqa')], default='teacher', max_length=20, verbose_name='Lavozim')),
                ('employment_type', models.CharField(choices=[('fixed', 'Belgilangan oylik'), ('hourly', 'Soatbay'), ('per_student', "O'quvchi soniga qarab"), ('mixed', 'Aralash (oylik + KPI)')], default='mixed', max_length=20, verbose_name='Ish turi')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Belgilangan oylik (so'm)")),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Soatlik stavka (so'm)")),
                ('per_student_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Har bir o'quvchi uchun (so'm)")),
                ('kpi_bonus_pct', models.DecimalField(decimal_places=2, default=Decimal('20'), help_text="Davomat va o'zlashtirishga qarab beriladigan maksimal bonus foizi.", max_digits=5, verbose_name='KPI bonusi (oylikning %)')),
                ('late_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Bitta kechikish jarimasi (so'm)")),
                ('card_number', models.CharField(blank=True, max_length=30, verbose_name='Plastik karta')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Ishga kirgan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Oy')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('closed', 'Yopilgan')], default='draft', max_length=10, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oylik davri',
                'verbose_name_plural': 'Oylik davrlari',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_days', models.PositiveSmallIntegerField(default=0, verbose_name='Ishlagan kunlar')),
                ('worked_hours', models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='Ishlagan soatlar')),
                ('lessons_count', models.PositiveIntegerField(default=0, verbose_name="O'tilgan darslar")),
                ('groups_count', models.PositiveIntegerField(default=0, verbose_name='Guruhlar soni')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name="O'quvchilar soni")),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Davomat (%)')),
                ('avg_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="O'rtacha o'zlashtirish (%)")),
                ('late_count', models.PositiveSmallIntegerField(default=0, verbose_name='Kechikishlar')),
                ('absence_count', models.PositiveSmallIntegerField(default=0, verbose_name='Sababsiz kelmaslik')),
                ('manual_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Qo'shimcha bonus (so'm)")),
                ('manual_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Qo'shimcha jarima (so'm)")),
                ('metrics_note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('students_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kpi_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalties_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Jami (so'm)")),
                ('kpi_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="KPI ko'rsatkichi (0-100)")),
                ('breakdown', models.JSONField(blank=True, default=dict, verbose_name='Tarkib')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='AI tahlili')),
                ('ai_recommendation', models.TextField(blank=True, verbose_name='AI tavsiyasi')),
                ('ai_rating', models.CharField(blank=True, max_length=20, verbose_name='AI bahosi')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='AI ishlatildi')),
                ('ai_model', models.CharField(blank=True, max_length=60, verbose_name='AI model')),
                ('status', models.CharField(choices=[('draft', 'Hisoblandi'), ('approved', 'Tasdiqlandi'), ('paid', "To'landi")], default='draft', max_length=10, verbose_name='Holat')),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hisoblangan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='salaries.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='salaries.salaryperiod')),
            ],
            options={
                'verbose_name': 'Oylik yozuvi',
                'verbose_name_plural': 'Oylik yozuvlari',
                'ordering': ['-period__year', '-period__month', 'employee__full_name'],
                'unique_together': {('period', 'employee')},
            },
        ),
    ]
