# Generated by Django 6.0.4 on 2026-06-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fan Lider', max_length=120, verbose_name='Markaz nomi')),
                ('tagline', models.CharField(blank=True, default="O'quv markazi boshqaruv tizimi", max_length=200, verbose_name='Shior / qisqa tavsif')),
                ('phone', models.CharField(blank=True, default='+998 90 000 00 00', max_length=40, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, default='Toshkent sh.', max_length=255, verbose_name='Manzil')),
                ('working_hours', models.CharField(blank=True, default='Dushanba–Shanba, 09:00–19:00', max_length=120, verbose_name='Ish vaqti')),
                ('about', models.TextField(blank=True, default='', verbose_name='Markaz haqida')),
                ('telegram_bot_username', models.CharField(blank=True, default='', help_text='Masalan: fan_lider_crm_bot', max_length=64, verbose_name='Telegram bot (@siz)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='center/', verbose_name='Logo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Markaz ma'lumotlari",
                'verbose_name_plural': "Markaz ma'lumotlari",
            },
        ),
    ]
