# Generated by Django 6.0.4 on 2026-05-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('purpose', models.CharField(choices=[('signup', "Ro'yxatdan o'tish"), ('reset', 'Parolni tiklash')], default='signup', max_length=20, verbose_name='Maqsad')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name="Ma'lumotlar")),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Urinishlar')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
            ],
            options={
                'verbose_name': 'Tasdiqlash kodi',
                'verbose_name_plural': 'Tasdiqlash kodlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
