# Generated by Django 6.0.4 on 2026-06-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Parol yangilanishi shart'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, default='', help_text="Admin yaratgan parol — faqat admin panelida ko'rinadi.", max_length=128, verbose_name="Ko'rinadigan parol"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('director', 'Direktor'), ('teacher', "O'qituvchi"), ('student', "O'quvchi")], default='student', max_length=20, verbose_name='Rol'),
        ),
    ]
