# Generated by Django 6.0.4 on 2026-06-04 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_must_change_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', "O'qituvchi"), ('student', "O'quvchi")], max_length=20, verbose_name='Rol')),
                ('identifier', models.CharField(help_text='Foydalanuvchi botda kiritgan login yoki telefon.', max_length=150, verbose_name='Login / telefon')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Ism (botdan)')),
                ('telegram_chat_id', models.CharField(db_index=True, max_length=32, verbose_name='Telegram chat ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('resolved', 'Yangi parol berildi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='Topilgan foydalanuvchi')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='Hal qilgan admin')),
            ],
            options={
                'verbose_name': 'Parol tiklash murojaati',
                'verbose_name_plural': 'Parol tiklash murojaatlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
