# Generated by Django 6.0.4 on 2026-06-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=32, verbose_name='Telegram chat ID')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('purpose', models.CharField(choices=[('signup', "Ro'yxatdan o'tish"), ('reset', 'Parolni tiklash')], default='signup', max_length=20, verbose_name='Maqsad')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name="Ma'lumotlar")),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Urinishlar')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
            ],
            options={
                'verbose_name': 'Tasdiqlash kodi',
                'verbose_name_plural': 'Tasdiqlash kodlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Telegram bot bergan ID — tasdiqlash kodi shu yerga yuboriladi.', max_length=32, verbose_name='Telegram chat ID'),
        ),
    ]
