# Generated by Django 6.0.4 on 2026-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_telegramverificationcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramverificationcode',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram bot'), ('email', 'Gmail')], default='telegram', max_length=10, verbose_name='Kanal'),
        ),
        migrations.AddField(
            model_name='telegramverificationcode',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='chat_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Telegram chat ID'),
        ),
    ]
