# Generated by Django 6.0.4 on 2026-05-31 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('color', models.CharField(default='#D4640F', max_length=7, verbose_name='Rang')),
                ('icon', models.CharField(default='📘', max_length=10, verbose_name='Belgi (emoji)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Guruh nomi')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Oylik to'lov (so'm)")),
                ('duration_months', models.PositiveIntegerField(default=3, verbose_name='Davomiyligi (oy)')),
                ('capacity', models.PositiveIntegerField(default=15, verbose_name="Sig'im (max o'quvchi)")),
                ('weekdays', models.CharField(choices=[('mon_wed_fri', 'Du-Chor-Juma'), ('tue_thu_sat', 'Se-Pay-Shan'), ('everyday', 'Har kuni'), ('weekend', 'Dam olish kunlari')], default='mon_wed_fri', max_length=20, verbose_name='Dars kunlari')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Xona')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('status', models.CharField(choices=[('recruiting', 'Qabul ochiq'), ('ongoing', 'Davom etmoqda'), ('finished', 'Yakunlangan'), ('paused', "Vaqtincha to'xtatilgan")], default='recruiting', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='instructors.instructor', verbose_name="O'qituvchi")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.subject', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
