# Generated by Django 6.0.4 on 2026-06-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, help_text='Masalan: Beginner, Elementary, Intermediate, A1, B2 ...', max_length=60, verbose_name='Daraja / level'),
        ),
    ]
