# Generated by Django 6.0.4 on 2026-05-31 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('specialty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mutaxassislik')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Oylik (so'm)")),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
